import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="nav-var">
              <div className="logo" href="/"><a>DS_HOME</a></div>
              <div className="nav-menu">
                <ul>
                  <li>
                    <a className="item" href="/my_portfolio/">Home</a>
                  </li>
                  <li>
                    <a className="item" href="About">About</a>
                  </li>
                  <li>
                    <a className="item" href="Project">Project</a>
                  </li>
                </ul>
              </div>
          </div>
        </header>

        {children}

        <footer>
            연습용 웹 페이지
        </footer>
      </body>
    </html>
  );
}
